---
- hosts : all
- name: Install Apache2 on Debian Nodes
  hosts: debian_servers
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes
