---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Apache on RedHat
      dnf:
        name: httpd
        state: present 
      when: ansible_os_family == "RedHat"
        
    - name: Start Apache on RedHat
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
      
    - name: Install Apache on Debian
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Apache2 service is enabled and running on Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
